---
# tasks file for apache
- name: Installation du serveur apache
  yum:
   name: httpd
   state: present

- name: desactivation du firewalld
  systemd:
   name: firewalld
   state: stopped
   enabled: no

- name: activation du serveur apache
  systemd:
   name: httpd
   state: started
   enabled: yes
